language: python
python:
- 3.7
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ark0015
  password:
    secure: qjIYrJLHwxobvwBCcoSXO/kc08t/4q40q07mrN8dXiGjNAHm9+109ErcqDiwTVaaAiq9O4syK4wecd/QY4sGN25/nxwsPXa78gtNztLxT6kgkFxg3DkYVWwWpOR+JvBdQmjgB7NneqI1tYZdQ3/5KzInwnRQSfUz+LMI4Mr/bieM61K6xBZwQ/uE2d/K6uJQj1WZogcC+RiIQ+TtJI/RfCdVsZdFImgHLhxZMp3wIGDEtZzQIPVvHniM+bKy2VtCq35N8O9Gecg5GSUNi2EEHo3nBYDfl5l/EXxkI522uow4oTaEEDFr95K9BlUA6bcQjcXNs+uEHC9AgZDoIeNmkKpi3MZ8j5OnkAc2SsgFZy64t1yOe6K2hazDRO2oTYLg9QumoLWWWo4zYu08RP+drGPqRyeUMYkw7sDJWliSbc0jnQ0znO74lNkZGrpf1lbiwTuEe3Zgc0WRU5cQbk8w5AvtVaNCOCpvqPpYD7dXxCle3ot3lsixzazQDmeA22crTpHhUcWmd+x+ITDgCcZzBh2FlqEQOv4T438RrX+X3mE0TzIt/xbfexpXr/BfUJkPMakaL6esY3bgHCHYxU4jml1f04QFhPUpQZ4ddO/1WQRgJFhsewv6xqTrPz3LO8KAEqGuOlb4zqM7McZ1RcLqRjwd/lBSckcRXgzCFtaCiZE=
  on:
    tags: true
    repo: ark0015/gwent
    python: 3.6